// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxZEYMsg07Zjo1ZhUfjNw8Gf80s78b6O0',
    appId: '1:671117420189:web:0697f7e91488840710d674',
    messagingSenderId: '671117420189',
    projectId: 'mynotes-bda5a',
    authDomain: 'mynotes-bda5a.firebaseapp.com',
    storageBucket: 'mynotes-bda5a.appspot.com',
    measurementId: 'G-9997N4NC8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUb99pblSX32ZvC1E-IorTHxQ3JKWXdBE',
    appId: '1:671117420189:android:54c557d3f0e1794c10d674',
    messagingSenderId: '671117420189',
    projectId: 'mynotes-bda5a',
    storageBucket: 'mynotes-bda5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWLsBtEY6glfbbDTzdCg4TYnZ1N4J-teo',
    appId: '1:671117420189:ios:a82c6a5ed557c98d10d674',
    messagingSenderId: '671117420189',
    projectId: 'mynotes-bda5a',
    storageBucket: 'mynotes-bda5a.appspot.com',
    iosBundleId: 'com.codine.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWLsBtEY6glfbbDTzdCg4TYnZ1N4J-teo',
    appId: '1:671117420189:ios:b71707f6aa7482e010d674',
    messagingSenderId: '671117420189',
    projectId: 'mynotes-bda5a',
    storageBucket: 'mynotes-bda5a.appspot.com',
    iosBundleId: 'com.codine.mynotes.RunnerTests',
  );
}
